from enum import Enum


class Country(Enum):
    AFGHANISTAN = ("Afghanistan", "AF", "Q889")
    ALBANIA = ("Albania", "AL", "Q222")
    ALGERIA = ("Algeria", "DZ", "Q262")
    ANDORRA = ("Andorra", "AD", "Q228")
    ANGOLA = ("Angola", "AO", "Q916")
    ANTIGUA_AND_BARBUDA = ("Antigua and Barbuda", "AG", "Q781")
    ARGENTINA = ("Argentina", "AR", "Q414")
    ARMENIA = ("Armenia", "AM", "Q399")
    AUSTRALIA = ("Australia", "AU", "Q408")
    AUSTRIA = ("Austria", "AT", "A40")
    AZERBAIJAN = ("Azerbaijan", "AZ", "Q227")
    BAHAMAS = ("The Bahamas", "BS", "Q778")
    BAHRAIN = ("Bahrain", "BH", "Q398")
    BANGLADESH = ("Bangladesh", "BD", "Q902")
    BARBADOS = ("Barbados", "BB", "Q244")
    BELARUS = ("Belarus", "BY", "Q184")
    BELGIUM = ("Belgium", "BE", "Q31")
    BELIZE = ("Belize", "BZ", "Q242")
    BENIN = ("Benin", "BJ", "BQ962")
    BHUTAN = ("Bhutan", "BT", "Q917")
    BOLIVIA = ("Bolivia", "BO", "Q750")
    BOSNIA_AND_HERZEGOVINA = ("Bosnia and Herzegovina", "BA", "Q225")
    BOTSWANA = ("Botswana", "BW", "Q963")
    BRAZIL = ("Brazil", "BR", "Q155")
    BRUNEI = ("Brunei", "BN", "Q921")
    BULGARIA = ("Bulgaria", "BG", "Q219")
    BURKINA_FASO = ("Burkina Faso", "BF", "Q965")
    BURUNDI = ("Burundi", "BI", "Q967")
    CABO_VERDE = ("Cabo Verde", "CV", "Q1011")
    CAMBODIA = ("Cambodia", "KH", "Q424")
    CAMEROON = ("Cameroon", "CM", "Q1009")
    CANADA = ("Canada", "CA", "Q16")
    CENTRAL_AFRICAN_REPUBLIC = ("Central African Republic", "CF", "Q929")
    CHAD = ("Chad", "TD", "Q657")
    CHILE = ("Chile", "CL", "Q298")
    CHINA = ("China", "CN", "Q148")
    COLOMBIA = ("Colombia", "CO", "Q739")
    COMOROS = ("Comoros", "KM", "Q970")
    CONGO = ("Congo", "CG", "Q971")
    CONGO_DR = ("Congo (Democratic Republic)", "CD", "Q974")
    COSTA_RICA = ("Costa Rica", "CR", "Q800")
    COTE_D_IVOIRE = ("Côte d'Ivoire", "CI", "Q1008")
    CROATIA = ("Croatia", "HR", "Q224")
    CUBA = ("Cuba", "CU", "Q241")
    CYPRUS = ("Cyprus", "CY", "Q229")
    CZECH_REPUBLIC = ("Czech Republic", "CZ", "Q213")
    DENMARK = ("Denmark", "DK", "Q35")
    DJIBOUTI = ("Djibouti", "DJ", "Q977")
    DOMINICA = ("Dominica", "DM", "Q784")
    DOMINICAN_REPUBLIC = ("Dominican Republic", "DO", "Q786")
    EAST_TIMOR = ("East Timor (Timor-Leste)", "TL", "Q574")
    ECUADOR = ("Ecuador", "EC", "Q736")
    EGYPT = ("Egypt", "EG", "Q79")
    EL_SALVADOR = ("El Salvador", "SV", "Q792")
    EQUATORIAL_GUINEA = ("Equatorial Guinea", "GQ", "Q983")
    ERITREA = ("Eritrea", "ER", "Q986")
    ESTONIA = ("Estonia", "EE", "Q191")
    ESWATINI = ("Eswatini", "SZ", "Q1050")
    ETHIOPIA = ("Ethiopia", "ET", "Q115")
    FIJI = ("Fiji", "FJ", "Q712")
    FINLAND = ("Finland", "FI", "Q33")
    FRANCE = ("France", "FR", "Q142")
    GABON = ("Gabon", "GA", "Q1000")
    GAMBIA = ("The Gambia", "GM", "Q1005")
    GEORGIA = ("Georgia", "GE", "Q230")
    GERMANY = ("Germany", "DE", "Q183")
    GHANA = ("Ghana", "GH", "Q117")
    GREECE = ("Greece", "GR", "Q41")
    GREENLAND = ("Greenland", "GL", "Q223")
    GRENADA = ("Grenada", "GD", "Q769")
    GUATEMALA = ("Guatemala", "GT", "Q774")
    GUINEA = ("Guinea", "GN", "Q1006")
    GUINEA_BISSAU = ("Guinea-Bissau", "GW", "Q1007")
    GUYANA = ("Guyana", "GY", "Q734")
    HAITI = ("Haiti", "HT", "Q790")
    HONDURAS = ("Honduras", "HN", "Q783")
    HUNGARY = ("Hungary", "HU", "Q28")
    ICELAND = ("Iceland", "IS", "Q189")
    INDIA = ("India", "IN", "Q668")
    INDONESIA = ("Indonesia", "ID", "Q252")
    IRAN = ("Iran", "IR", "Q794")
    IRAQ = ("Iraq", "IQ", "Q796")
    IRELAND = ("Ireland", "IE", "Q27")
    ISRAEL = ("Israel", "IL", "Q801")
    ITALY = ("Italy", "IT", "Q38")
    JAMAICA = ("Jamaica", "JM", "Q766")
    JAPAN = ("Japan", "JP", "Q17")
    JORDAN = ("Jordan", "JO", "Q810")
    KAZAKHSTAN = ("Kazakhstan", "KZ", "Q232")
    KENYA = ("Kenya", "KE", "Q114")
    KIRIBATI = ("Kiribati", "KI", "Q710")
    KOSOVO = ("Kosovo", "XK", "Q1246")
    KUWAIT = ("Kuwait", "KW", "Q817")
    KYRGYZSTAN = ("Kyrgyzstan", "KG", "Q813")
    LAOS = ("Laos", "LA", "Q819")
    LATVIA = ("Latvia", "LV", "Q211")
    LEBANON = ("Lebanon", "LB", "Q822")
    LESOTHO = ("Lesotho", "LS", "Q1013")
    LIBERIA = ("Liberia", "LR", "Q1014")
    LIBYA = ("Libya", "LY", "Q1016")
    LIECHTENSTEIN = ("Liechtenstein", "LI", "Q347")
    LITHUANIA = ("Lithuania", "LT", "Q37")
    LUXEMBOURG = ("Luxembourg", "LU", "Q32")
    MADAGASCAR = ("Madagascar", "MG", "Q1019")
    MALAWI = ("Malawi", "MW", "Q1020")
    MALAYSIA = ("Malaysia", "MY", "Q833")
    MALDIVES = ("Maldives", "MV", "Q826")
    MALI = ("Mali", "ML", "Q912")
    MALTA = ("Malta", "MT", "Q233")
    MARSHALL_ISLANDS = ("Marshall Islands", "MH", "Q709")
    MAURITANIA = ("Mauritania", "MR", "Q1025")
    MAURITIUS = ("Mauritius", "MU", "Q1027")
    MEXICO = ("Mexico", "MX", "Q96")
    MICRONESIA = ("Micronesia (Federated States)", "FM", "Q702")
    MOLDOVA = ("Moldova", "MD", "Q217")
    MONACO = ("Monaco", "MC", "Q235")
    MONGOLIA = ("Mongolia", "MN", "Q711")
    MONTENEGRO = ("Montenegro", "ME", "Q236")
    MOROCCO = ("Morocco", "MA", "Q1028")
    MOZAMBIQUE = ("Mozambique", "MZ", "Q1029")
    MYANMAR = ("Myanmar", "MM", "Q836")
    NAMIBIA = ("Namibia", "NA", "Q1030")
    NAURU = ("Nauru", "NR", "Q697")
    NEPAL = ("Nepal", "NP", "Q837")
    NETHERLANDS = ("Netherlands", "NL", "Q55")
    NEW_ZEALAND = ("New Zealand", "NZ", "Q664")
    NICARAGUA = ("Nicaragua", "NI", "Q811")
    NIGER = ("Niger", "NE", "Q1032")
    NIGERIA = ("Nigeria", "NG", "Q1033")
    NORTH_KOREA = ("North Korea (DPRK)", "KP", "Q423")
    NORTH_MACEDONIA = ("North Macedonia", "MK", "Q221")
    NORWAY = ("Norway", "NO", "Q20")
    OMAN = ("Oman", "OM", "Q842")
    PAKISTAN = ("Pakistan", "PK", "Q843")
    PALAU = ("Palau", "PW", "Q695")
    PANAMA = ("Panama", "PA", "Q804")
    PAPUA_NEW_GUINEA = ("Papua New Guinea", "PG", "Q691")
    PARAGUAY = ("Paraguay", "PY", "Q733")
    PERU = ("Peru", "PE", "Q419")
    PHILIPPINES = ("Philippines", "PH", "Q928")
    POLAND = ("Poland", "PL", "Q36")
    PORTUGAL = ("Portugal", "PT", "Q45")
    QATAR = ("Qatar", "QA", "Q846")
    ROMANIA = ("Romania", "RO", "Q218")
    RUSSIA = ("Russia", "RU", "Q159")
    RWANDA = ("Rwanda", "RW", "Q1037")
    SAINT_KITTS_AND_NEVIS = ("Saint Kitts and Nevis", "KN", "Q763")
    SAINT_LUCIA = ("Saint Lucia", "LC", "Q760")
    SAINT_VINCENT_AND_THE_GRENADINES = ("Saint Vincent and the Grenadines", "VC", "Q757")
    SAMOA = ("Samoa", "WS", "Q683")
    SAN_MARINO = ("San Marino", "SM", "Q238")
    SAO_TOME_AND_PRINCIPE = ("São Tomé and Principe", "ST", "Q1039")
    SAUDI_ARABIA = ("Saudi Arabia", "SA", "Q851")
    SENEGAL = ("Senegal", "SN", "Q1041")
    SERBIA = ("Serbia", "RS", "Q403")
    SEYCHELLES = ("Seychelles", "SC", "Q1042")
    SIERRA_LEONE = ("Sierra Leone", "SL", "Q1044")
    SINGAPORE = ("Singapore", "SG", "Q334")
    SLOVAKIA = ("Slovakia", "SK", "Q214")
    SLOVENIA = ("Slovenia", "SI", "Q215")
    SOLOMON_ISLANDS = ("Solomon Islands", "SB", "Q685")
    SOMALIA = ("Somalia", "SO", "Q1045")
    SOUTH_AFRICA = ("South Africa", "ZA", "Q258")
    SOUTH_KOREA = ("South Korea", "KR", "Q884")
    SOUTH_SUDAN = ("South Sudan", "SS", "Q958")
    SPAIN = ("Spain", "ES", "Q29")
    SRI_LANKA = ("Sri Lanka", "LK", "Q854")
    SUDAN = ("Sudan", "SD", "Q1049")
    SURINAME = ("Suriname", "SR", "Q730")
    SWEDEN = ("Sweden", "SE", "Q34")
    SWITZERLAND = ("Switzerland", "CH", "Q39")
    SYRIA = ("Syria", "SY", "Q858")
    TAIWAN = ("Taiwan", "TW", "Q865")
    TAJIKISTAN = ("Tajikistan", "TJ", "Q863")
    TANZANIA = ("Tanzania", "TZ", "Q924")
    THAILAND = ("Thailand", "TH", "Q869")
    TOGO = ("Togo", "TG", "Q945")
    TONGA = ("Tonga", "TO", "Q678")
    TRINIDAD_AND_TOBAGO = ("Trinidad and Tobago", "TT", "Q754")
    TUNISIA = ("Tunisia", "TN", "Q948")
    TURKEY = ("Turkey", "TR", "Q43")
    TURKMENISTAN = ("Turkmenistan", "TM", "Q874")
    TUVALU = ("Tuvalu", "TV", "Q672")
    UGANDA = ("Uganda", "UG", "Q1036")
    UKRAINE = ("Ukraine", "UA", "Q212")
    UNITED_ARAB_EMIRATES = ("United Arab Emirates", "AE", "Q878")
    UNITED_KINGDOM = ("United Kingdom", "GB", "Q145")
    UNITED_STATES_OF_AMERICA = ("United States of America", "US", "Q30")
    URUGUAY = ("Uruguay", "UY", "Q77")
    UZBEKISTAN = ("Uzbekistan", "UZ", "Q265")
    VANUATU = ("Vanuatu", "VU", "Q686")
    VATICAN_CITY = ("Vatican City", "VA", "Q237")
    VENEZUELA = ("Venezuela", "VE", "Q717")
    VIETNAM = ("Vietnam", "VN", "Q881")
    YEMEN = ("Yemen", "YE", "Q805")
    ZAMBIA = ("Zambia", "ZM", "Q953")
    ZIMBABWE = ("Zimbabwe", "ZW", "Q954")

    def __new__(cls, value, code, wikidata):
        obj = object.__new__(cls)
        obj._value_ = value
        obj.code = code
        obj.wikidata = wikidata

        return obj


class Language(Enum):
    AFRIKAANS = "Afrikaans"
    AKAN = "Akan"
    ALBANIAN = "Albanian"
    AMHARIC = "Amharic"
    ARABIC = "Arabic"
    ARMENIAN = "Armenian"
    ASSAMESE = "Assamese"
    AYMARA = "Aymara"
    AZERBAIJANI = "Azerbaijani"
    BAMBARA = "Bamara"
    BANGLA = "Bangla"
    BASQUE = "Basque"
    BELARUSIAN = "Belarusian"
    BHOJPURI = "Bhojpuri"
    BOSNIAN = "Bosnian"
    BULGARIAN = "Bulgarian"
    BURMESE = "Burmese"
    CATALAN = "Catalan"
    CEBUANO = "Cebuano"
    CHINESE_SIMPLIFIED = "Chinese (Simplified)"
    CHINESE_TRADITIONAL = "Chinese (Traditional)"
    CORSICAN = "Corsican"
    CROATIAN = "Croatian"
    CZECH = "Czech"
    DANISH = "Danish"
    DIVEHI = "Divehi"
    DOGRI = "Dogri"
    DUTCH = "Dutch"
    ENGLISH = "English"
    ESPERANTO = "Esperanto"
    ESTONIAN = "Estonian"
    EWE = "Ewe"
    FILIPINO = "Filipino"
    FINNISH = "Finnish"
    FRENCH = "French"
    FRISIAN = "Frisian"
    GALICIAN = "Galician"
    GANDA = "Ganda"
    GEORGIAN = "Georgian"
    GERMAN = "German"
    GOAN_KONKANI = "Goan Konkani"
    GREEK = "Greek"
    GUARANI = "Guarani"
    GUJARATI = "Gujarati"
    HAITIAN_CREOLE = "Haitian Creole"
    HAUSA = "Hausa"
    HAWAIIAN = "Hawaiian"
    HEBREW = "Hebrew"
    HINDI = "Hindi"
    HMONG = "Hmong"
    HUNGARIAN = "Hungarian"
    ICELANDIC = "Icelandic"
    IGBO = "Igbo"
    ILOKO = "Iloko"
    INDONESIAN = "Indonesian"
    IRISH = "Irish"
    ITALIAN = "Italian"
    JAPANESE = "Japanese"
    JAVANESE = "Javanese"
    KANNADA = "Kannada"
    KAZAKH = "Kazakh"
    KHMER = "Khmer"
    KINYARWANDA = "Kinyarwanda"
    KOREAN = "Korean"
    KRIO = "Krio"
    KURDISH = "Kurdish"
    KURDISH_CENTRAL = "Central Kurdish"
    KYGRYZ = "Kygryz"
    LAO = "Lao"
    LATIN = "Latin"
    LATVIAN = "Latvian"
    LINGALA = "Lingala"
    LITHUANIAN = "Lithuanian"
    LUXEMBOURGISH = "Luxembourgish"
    MACEDONIAN = "Macedonian"
    MAITHILI = "Maithili"
    MALAGASY = "Malagasy"
    MALAY = "Malay"
    MALAYALAM = "Malayalam"
    MALTESE = "Maltese"
    MANIPURI = "Manipuri"
    MAORI = "Māori"
    MARATHI = "Marathi"
    MIZO = "Mizo"
    MONGOLIAN = "Mongolian"
    NEPALI = "Nepali"
    NORWEGIAN = "Norwegian"
    NYANJA = "Nyanja"
    ODIA = "Odia"
    OROMO = "Oromo"
    PASHTO = "Pashto"
    PERSIAN = "Persian"
    POLISH = "Polish"
    PORTUGUESE = "Portuguese"
    PUNJABI = "Punjabi"
    QUECHUA = "Quechua"
    ROMANIAN = "Romanian"
    RUSSIAN = "Russian"
    SAMOAN = "Samoan"
    SANSKRIT = "Sanskrit"
    SCOTTISH_GAELIC = "Scottish Gaelic"
    SERBIAN = "Serbian"
    SHONA = "Shona"
    SINDHI = "Sindhi"
    SINDHALA = "Sindhala"
    SLOVAK = "Slovak"
    SLOVENIAN = "Slovenian"
    SOMALI = "Somali"
    SOTHO = "Sotho"
    SPANISH = "Spanish"
    SUDANESE = "Sudanese"
    SWAHILI = "Swahili"
    SWEDISH = "Swedish"
    TAJIK = "Tajik"
    TAMIL = "Tamil"
    TATAR = "Tatar"
    TELUGU = "Telugu"
    THAI = "Thai"
    TIGRINYA = "Tigrinya"
    TSONGA = "Tsonga"
    TURKISH = "Turkish"
    TURKMEN = "Turkmen"
    UKRAINIAN = "Ukrainian"
    URDU = "Urdu"
    UYGHUR = "Uyghur"
    UZBEK = "Uzbek"
    VIETNAMESE = "Vietnamese"
    WELSH = "Welsh"
    XHOSA = "Xhosa"
    YIDDISH = "Yiddish"
    YORUBA = "Yoruba"


class Media(Enum):
    ACETATE = "Acetate"
    BETACAM = "Betacam"
    BETACAM_SP = "Betacam SP"
    BETAMAX = "Betamax"
    BLURAY = "Blu-ray"
    BLURAYR = "Blu-ray-R"
    BLURAY_ULTRA_HD = "Ultra HD Blu-ray"
    CARTRIVISION = "Cartrivision"
    CART_4_TRACK = "4-Track Cartridge"
    CART_8_TRACK = "8-Track Cartridge"
    CART_8_TRACK_QUAD = "Quad 8-Track Cartridge"
    CART_RCA_TAPE = "RCA Tape Cartridge"
    CART_REVERE_MAGNETIC_STEREO_TAPE = "Revere Magnetic Stereo Tape Cartridge"
    CASSETTE = "Cassette"
    CASSETTE_NT = "NT Cassette"
    CD = "CD"
    CDE = "Enhanced CD"
    CDG = "CD+G"
    CDR = "CD-R"
    CDV = "CD-V"
    CD_HD = "HDCD"
    CD_SHM = "SHM-CD"
    CED = "CED"
    DAT = "DAT"
    DCC = "DCC"
    DC_INTERNATIONAL = "DC-International"
    DISC_EDISON = "Edison Diamond Disc"
    DISC_FLEXI = "Flexi-Disc"
    DISC_PATHE = "Pathé Disc"
    DUALDISC = "DualDisc"
    DVD = "DVD"
    DVDR = "DVD-R"
    DVD_HD = "HD DVD"
    DVD_PLUS = "DVDplus"
    DVDR_HD = "HD DVD-R"
    ELCASET = "Elcaset"
    FILE = "File"
    FILM_REEL = "Film Reel"
    FLOPPY_DISK = "Floppy Disk"
    HIPAC = "HiPac"
    HITCLIPS = "HitClips"
    HYBRID = "Hybrid Format"
    LASERDISC = "LaserDisc"
    LATHE_CUT = "Lathe Cut"
    MEMORY_STICK = "Memory Stick"
    MICROCASSETTE = "Microcassette"
    MIGHTY_TINY = "Mighty Tiny"
    MINIDISC = "MiniDisc"
    MINIDV = "MiniDV"
    MUSIC_CARD = "Music Card"
    MVD = "MVD"
    PIANO_ROLL = "Piano Roll"
    PLAYBUTTON = "Playbutton"
    PLAYTAPE = "PlayTape"
    POCKET_ROCKER = "Pocket Rocker"
    REEL_TO_REEL = "Reel-To-Reel"
    SABAMOBIL = "Sabamobil"
    SACD = "SACD"
    SACD_HYBRID = "Hybrid SACD"
    SACD_SHM = "SHM-SACD"
    SD_CARD = "SD Card"
    SELECTAVISION = "SelectaVision"
    SHELLAC = "Shellac"
    SLOTMUSIC = "SlotMusic"
    SOPIC = "Sopic"
    TED = "TeD"
    TEFIFON = "Tefifon"
    UMATIC = "U-matic"
    UMD = "UMD"
    VHD = "VHD"
    VHS = "VHS"
    VHS_SUPER = "Super VHS"
    VIDEO_8 = "Video8"
    VIDEO_2000 = "Video 2000"
    VINYL = "Vinyl"
    VINYLDISC = "VinylDisc"
    WAX_CYLINDER = "Wax Cylinder"
    WIRE = "Wire Recording"
    ZIP_DISK = "Zip Disk"


class ReleaseType(Enum):
    DEMO = "Demo"
    DJ_MIX = "DJ Mix"
    EP = "Extended Play"
    COMPILATION = "Compilation"
    INTERVIEW = "Interview"
    LIVE = "Live"
    OTHER = "Other"
    REMIX = "Remix"
    SINGLE = "Single"
    SOUNDTRACK = "Soundtrack"
    STUDIO = "Studio"
    VIDEO = "Video Album"
